os: osx
osx_image: xcode12.3
language: swift
script: xcodebuild clean build test -workspace SwiftyMovies.xcworkspace -scheme "CI" -destination "platform=iOS Simulator,name=iPhone 12,OS=14.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
